### ISSUE TITLE
Ray Tracer doesnt work

### ISSUE THREAD

**Issue by kry0sc0pic** [SuketuPatni/hyperion#1] opened 2022-04-19 14:06 UTC
couldnt run roblox at 16K 500FPS with ray tracing.

disappointed in you @SuketuPatni.

**Comment by SuketuPatni** [comment] 2022-04-19 14:15
Nice issue, however, this leads to a trilemma for you:-
a. You don't have Rust installed on any of your computers bruv, how do you know it can't?
b. In case you do have Rust installed on some device, my objective of making this Ray Tracer is already fulfilled, and I have successfully converted you into a Rustacean.
c. If you want to be clever you would install Rust, test the tracer, and uninstall it again, thereby refuting points (a) and (b). However, there would be nothing stopping me from making some minor improvements to my code and claiming that the issue has been fixed.

**Comment by kry0sc0pic** [comment] 2022-04-19 14:19
imma fix this polylemma real quick.

I have rust installed but that doesn't make me a Rustacean since I don't(can't) code in rust and i tried running it with roobloox and it didnt work.

**Comment by SuketuPatni** [comment] 2022-04-19 14:22
Au contraire, my friend: [Rustacean Definition](https://en.wiktionary.org/wiki/Rustacean)
User, and you've used the language to execute a program. It doesn't mention writing Rust code to be a requisite.

**Comment by kry0sc0pic** [comment] 2022-04-19 14:26
It says "User of the programming language". Now I didnt use rust once because I compiled the robloox exe on a remote docker server which was automatically triggered by a commit on some other repo. I merely happened to have the rust compiler installed.
Which doesnt make me a rustacean.

[@AdityaBhattacharya1](https://github.com/dityaBhattacharya1) back me up here

**Comment by AdityaBhattacharya1** [comment] 2022-04-19 14:35
Nice argument, Suketu. However, as a great person once said:
```
no method named into_par_iter found for struct std::iter::FlatMap<std::ops::RangeInclusive<i32>, std::iter::Map<std::ops::RangeInclusive<i32>, [closure@src\world\mod.rs:38:51: 38:69 x:_]>, [closure@src\world\mod.rs:37:52: 38:70 chunk_min:_, chunk_max:_]> in the current scope the method into_par_iter exists but the following trait bounds were not satisfied: std::iter::FlatMap<std::ops::RangeInclusive<i32>, std::iter::Map<std::ops::RangeInclusive<i32>, [closure@src\world\mod.rs:38:51: 38:69 x:_]>, [closure@src\world\mod.rs:37:52: 38:70 chunk_min:_, chunk_max:_]>: rayon::iter::ParallelIterator which is required by std::iter::FlatMap<std::ops::RangeInclusive<i32>, std::iter::Map<std::ops::RangeInclusive<i32>, [closure@src\world\mod.rs:38:51: 38:69 x:_]>, [closure@src\world\mod.rs:37:52: 38:70 chunk_min:_, chunk_max:_]>: rayon::iter::IntoParallelIterator &std::iter::FlatMap<std::ops::RangeInclusive<i32>, std::iter::Map<std::ops::RangeInclusive<i32>, [closure@src\world\mod.rs:38:51: 38:69 x:_]>, [closure@src\world\mod.rs:37:52: 38:70 chunk_min:_, chunk_max:_]>: rayon::iter::ParallelIterator which is required by &std::iter::FlatMap<std::ops::RangeInclusive<i32>, std::iter::Map<std::ops::RangeInclusive<i32>, [closure@src\world\mod.rs:38:51: 38:69 x:_]>, [closure@src\world\mod.rs:37:52: 38:70 chunk_min:_, chunk_max:_]>: rayon::iter::IntoParallelIterator &mut std::iter::FlatMap<std::ops::RangeInclusive<i32>, std::iter::Map<std::ops::RangeInclusive<i32>, [closure@src\world\mod.rs:38:51: 38:69 x:_]>, [closure@src\world\mod.rs:37:52: 38:70 chunk_min:_, chunk_max:_]>: rayon::iter::ParallelIterator which is required by &mut std::iter::FlatMap<std::ops::RangeInclusive<i32>, std::iter::Map<std::ops::RangeInclusive<i32>, [closure@src\world\mod.rs:38:51: 38:69 x:_]>, [closure@src\world\mod.rs:37:52: 38:70 chunk_min:_, chunk_max:_]>: rayon::iter::IntoParallelIterator
```
Rewrite in Rust.
Thanks

**Comment by SuketuPatni** [comment] 2022-04-19 14:44
Possible duplicate of [this](https://www.reddit.com/r/copypasta/comments/txjd49/it_is_year_2028_and_linux_has_been_completely/) and [this](https://insights.stackoverflow.com/survey/2021#most-loved-dreaded-and-wanted-language-love-dread)

**Comment by AdityaBhattacharya1** [comment] 2022-04-19 14:49
Hmm, is that so?
![image](https://user-images.githubusercontent.com/69953590/164031760-79eb5147-2445-41a6-b0c1-9f4e64ff8b23.png)
![image](https://user-images.githubusercontent.com/69953590/164031831-c3217853-554f-4b5e-8860-b2ab6d84c9c0.png)

**Comment by kry0sc0pic** [comment] 2022-04-19 15:03
And for fun write in COBOL as well.

![image](https://user-images.githubusercontent.com/62088268/164034842-085276fa-5d5a-454b-a637-8d3424942e9b.png)

**Comment by SuketuPatni** [comment] 2022-04-19 15:13
Alright gentlemen, this has been absolutely wonderful.

**Closed as completed** 2022-04-19 15:14 UTC
Labels: bug, enhancement, invalid

**Comment by kry0sc0pic** [comment] 2022-04-19 15:17
reopened cuz i had issue with code how i rewrite rust in rust

**Comment by kry0sc0pic** [comment] 2022-04-19 15:17
welp github issue fails unlucky
